# Generated by Django 5.0.5 on 2024-07-17 15:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anomalies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomaly",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="full_name",
            field=models.TextField(
                default="Test", max_length=100, verbose_name="Nom complet"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anomaly",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AddConstraint(
            model_name="anomaly",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("email__isnull", False), ("phone_number", None)),
                    models.Q(("email", None), ("phone_number__isnull", False)),
                    _connector="OR",
                ),
                name="one of phone_number and email must be not null",
            ),
        ),
    ]
