# Generated by Django 5.0.7 on 2024-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "anomalies",
            "0003_remove_anomaly_one_of_phone_number_and_email_must_be_not_null_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Nom complet"),
        ),
    ]
