name: rostrenen_et_moi
description: Rostrenen et moi
publish_to: 'none'

version: 2.0.5+14

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  form_builder_validators: ^11.0.0
  form_builder_image_picker: ^4.0.0
  intl: ^0.20.2
  go_router: ^16.0.0
  sqflite: ^2.2.8+4
  cross_file: ^0.3.3+4
  dio: ^5.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqlite3_flutter_libs: ^0.5.16
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  phone_form_field: ^10.0.8
  flutter_form_builder: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
